ignore:
  - "contracts/arbitrum"
  - "contracts/interfaces"
  - "contracts/library"
  - "test"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: null
    patch:
      default:
        target: 80%
        threshold: null